### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by MelanX** [ModdingX/mclogs#5]
As part of Modtoberfest, you can translate [this template](https://github.com/ModdingX/mclogs/blob/master/_mc-logs.md) to any language you’re familiar with. Use the country indicators as file name as done with `fr.md` for French or `de.md` for German. You can check if your indicators are correct by checking if they are responsible for the emoji flag of this country, for example `:de:` here in an issue.
If you want to submit multiple languages, please create a pull request for each language.

**Don't use a translator to translate everything, we want good translations, everything else could be done with a bot**

**Comment by IMB11** [comment]
See #7

**Comment by noeppi-noeppi** [comment]
Closed in favour of #13
